/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _openni_image_msg_t_h
#define _openni_image_msg_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define OPENNI_IMAGE_MSG_T_VIDEO_RGB 0
#define OPENNI_IMAGE_MSG_T_VIDEO_BAYER 1
#define OPENNI_IMAGE_MSG_T_VIDEO_RGB_JPEG 100
#define OPENNI_IMAGE_MSG_T_VIDEO_NONE 101

typedef struct _openni_image_msg_t openni_image_msg_t;
struct _openni_image_msg_t
{
    int64_t    timestamp;
    int16_t    width;
    int16_t    height;
    int16_t    pixel_offset[2];
    int32_t    image_data_nbytes;
    uint8_t    *image_data;
    int8_t     image_data_format;
};

openni_image_msg_t   *openni_image_msg_t_copy(const openni_image_msg_t *p);
void openni_image_msg_t_destroy(openni_image_msg_t *p);

typedef struct _openni_image_msg_t_subscription_t openni_image_msg_t_subscription_t;
typedef void(*openni_image_msg_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const openni_image_msg_t *msg, void *user);

int openni_image_msg_t_publish(lcm_t *lcm, const char *channel, const openni_image_msg_t *p);
openni_image_msg_t_subscription_t* openni_image_msg_t_subscribe(lcm_t *lcm, const char *channel, openni_image_msg_t_handler_t f, void *userdata);
int openni_image_msg_t_unsubscribe(lcm_t *lcm, openni_image_msg_t_subscription_t* hid);
int openni_image_msg_t_subscription_set_queue_capacity(openni_image_msg_t_subscription_t* subs,
                              int num_messages);


int  openni_image_msg_t_encode(void *buf, int offset, int maxlen, const openni_image_msg_t *p);
int  openni_image_msg_t_decode(const void *buf, int offset, int maxlen, openni_image_msg_t *p);
int  openni_image_msg_t_decode_cleanup(openni_image_msg_t *p);
int  openni_image_msg_t_encoded_size(const openni_image_msg_t *p);

// LCM support functions. Users should not call these
int64_t __openni_image_msg_t_get_hash(void);
int64_t __openni_image_msg_t_hash_recursive(const __lcm_hash_ptr *p);
int     __openni_image_msg_t_encode_array(void *buf, int offset, int maxlen, const openni_image_msg_t *p, int elements);
int     __openni_image_msg_t_decode_array(const void *buf, int offset, int maxlen, openni_image_msg_t *p, int elements);
int     __openni_image_msg_t_decode_array_cleanup(openni_image_msg_t *p, int elements);
int     __openni_image_msg_t_encoded_array_size(const openni_image_msg_t *p, int elements);
int     __openni_image_msg_t_clone_array(const openni_image_msg_t *p, openni_image_msg_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
