/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>
#include <lcm/lcm.h>

#ifndef _openni_frame_msg_t_h
#define _openni_frame_msg_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "openni_image_msg_t.h"
#include "openni_depth_msg_t.h"
#include "openni_disparity_msg_t.h"
typedef struct _openni_frame_msg_t openni_frame_msg_t;
struct _openni_frame_msg_t
{
    int64_t    timestamp;
    openni_image_msg_t image;
    openni_depth_msg_t depth;
    openni_disparity_msg_t disparity;
};

openni_frame_msg_t   *openni_frame_msg_t_copy(const openni_frame_msg_t *p);
void openni_frame_msg_t_destroy(openni_frame_msg_t *p);

typedef struct _openni_frame_msg_t_subscription_t openni_frame_msg_t_subscription_t;
typedef void(*openni_frame_msg_t_handler_t)(const lcm_recv_buf_t *rbuf,
             const char *channel, const openni_frame_msg_t *msg, void *user);

int openni_frame_msg_t_publish(lcm_t *lcm, const char *channel, const openni_frame_msg_t *p);
openni_frame_msg_t_subscription_t* openni_frame_msg_t_subscribe(lcm_t *lcm, const char *channel, openni_frame_msg_t_handler_t f, void *userdata);
int openni_frame_msg_t_unsubscribe(lcm_t *lcm, openni_frame_msg_t_subscription_t* hid);
int openni_frame_msg_t_subscription_set_queue_capacity(openni_frame_msg_t_subscription_t* subs,
                              int num_messages);


int  openni_frame_msg_t_encode(void *buf, int offset, int maxlen, const openni_frame_msg_t *p);
int  openni_frame_msg_t_decode(const void *buf, int offset, int maxlen, openni_frame_msg_t *p);
int  openni_frame_msg_t_decode_cleanup(openni_frame_msg_t *p);
int  openni_frame_msg_t_encoded_size(const openni_frame_msg_t *p);

// LCM support functions. Users should not call these
int64_t __openni_frame_msg_t_get_hash(void);
int64_t __openni_frame_msg_t_hash_recursive(const __lcm_hash_ptr *p);
int     __openni_frame_msg_t_encode_array(void *buf, int offset, int maxlen, const openni_frame_msg_t *p, int elements);
int     __openni_frame_msg_t_decode_array(const void *buf, int offset, int maxlen, openni_frame_msg_t *p, int elements);
int     __openni_frame_msg_t_decode_array_cleanup(openni_frame_msg_t *p, int elements);
int     __openni_frame_msg_t_encoded_array_size(const openni_frame_msg_t *p, int elements);
int     __openni_frame_msg_t_clone_array(const openni_frame_msg_t *p, openni_frame_msg_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
